theme: jekyll-theme-minimal
title: inlineditor
description: Inlineditor is a WYSIWYG editor for websites. Its goal is to be powerful and simple and configurable. Inlineditor is extremely lightweight and can be easily integrated in any web application.
